projects/mysite/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import(handler404, handler500)



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fanMonitoring.urls')),
    #path('common/', include('common.urls')),
]

projects/mysite/fanMonitoring/urls.py
from django.urls import path, include
from . import views

app_name = 'fanMonitoring'

urlpatterns = [
    path('', views.index, name='index'),
    path('cmh/', views.cmh, name='cmh'),
    path('network/', views.network, name='network'),
    path('iloInfo/', views.iloInfo, name='iloInfo'),
    path('logHome', views.logHome, name='logHome'),
    path('logCmh', views.logCmh, name='logCmh'),
    path('logNetwork', views.logNetwork, name='logNetwork'),
    path('logIloInfo', views.logIloInfo, name='logIloInfo'),
    path('registrationServerType', views.registrationServerType, name='registrationServerType'),
    path('registrationServer', views.registrationServer, name='registrationServer'),
]

projects/mysite/fanMonitoring/models.py
from tkinter import CASCADE
from django.db import models
# from django.db.models import F, Sum


class ServerType(models.Model):
    serverType = models.CharField(max_length = 200, default="ETC")

    def __str__(self):
        return self.serverType

class Server(models.Model):
    serverName = models.CharField(max_length=200, null=True)
    serverTypeId = models.ForeignKey(ServerType, on_delete=models.CASCADE)
    linuxIp = models.CharField(max_length=200)
    linuxId = models.CharField(max_length=200, default="root")
    linuxPw = models.CharField(max_length=200, default="cua001")
    iloIp = models.CharField(max_length=200)
    iloId = models.CharField(max_length=200, default = "Administrator")
    iloPw = models.CharField(max_length=200)
    sshPort = models.CharField(max_length=200, default = "22")

    def __str__(self):
        return self.serverName

class Cmh(models.Model):
    id = models.AutoField(primary_key=True)
    serverId = models.ForeignKey(Server, on_delete=models.CASCADE)
    cpu = models.FloatField()
    cpuStatus = models.BooleanField(default=False)
    mem = models.FloatField()
    memStatus = models.BooleanField(default=False)
    hdd = models.FloatField()
    hddStatus = models.BooleanField(default=False)
    time = models.DateTimeField(null=True)

    def __str__(self):
        return self.serverId.serverName

class Network(models.Model):
    id = models.AutoField(primary_key=True)
    serverId = models.ForeignKey(Server, on_delete=models.CASCADE)
    rxPps = models.FloatField()
    txPps = models.FloatField()
    time = models.DateTimeField(null = True)

    def __str__(self):
        return self.serverId.serverName

class Ilo(models.Model):
    id = models.AutoField(primary_key=True)
    serverId = models.ForeignKey(Server, on_delete=models.CASCADE)
    fan1=models.IntegerField(null = True)
    fan1Status = models.BooleanField(default = False)
    fan2=models.IntegerField(null = True)
    fan2Status = models.BooleanField(default=False)
    fan3=models.IntegerField(null = True)
    fan3Status = models.BooleanField(default=False)
    fan4=models.IntegerField(null = True)
    fan4Status = models.BooleanField(default=False)
    cpuThermal=models.FloatField(null = True)
    cpuThermalStatus = models.BooleanField(default=False)
    memThermal=models.FloatField(null = True)
    memThermalStatus = models.BooleanField(default = False)
    time = models.DateTimeField(null = True)

    def __str__(self):
        return self.serverId.serverName

class Connection(models.Model):
    id = models.AutoField(primary_key = True)
    serverId = models.ForeignKey(Server, on_delete=models.CASCADE)
    connectToLinux = models.BooleanField()
    connectToIlo = models.BooleanField()
    def __str__(self):
        return self.serverId.serverName
# Create your models here.

projects/mysite/fanMonitoring/forms.py
# from django import forms
# from fanMonitoring.models import *
# # from datetimewidget.widgets import DateTimeWidget
#
#
#
#
#
#
# class ServerForm(forms.ModelForm):
#     class Meta :
#         model = Server
#         fields = ['serverName', 'serverTypeId', 'linuxIp', 'linuxId', 'linuxPw', 'iloIp', 'iloId', 'iloPw', 'sshPort']
#
#         labels = {
#             'serverName' : '서버 이름',
#             'serverTypeId' : '서버 종류',
#             'linuxIp' : '서버 IP',
#             'linuxId' : '서버 ID',
#             'linuxPw' : '서버 PW',
#             'iloIp' : 'ILO IP',
#             'iloId' : 'ILO ID',
#             'iloPw' : 'ILO PW',
#             'sshPort' : 'SSH PORT',
#         }
#
#
# class ServerTypeForm(forms.ModelForm):
#     class Meta :
#         model = ServerType
#         fields = ['serverType']
#
#         labels = {
#             'serverType' : '서버 종류',
#         }

projects/mysite/fanMonitoring/views.py
from sys import flags
from django.http import HttpResponse
from django.shortcuts import redirect, render, get_object_or_404
# from numpy import _FlatIterSelf
from .models import *
from .forms import *
from django.contrib import messages
from django.db.models import F, Sum
from django.db import models
import datetime

# Create your views here.


def index(request):
    servers = Server.objects.all()
    connections = Connection.objects.all().order_by('serverId', '-id').distinct('serverId')
    context = {'servers':servers, 'connections' : connections}
    return render(request, 'fanMonitoring/index.html', context)

def registrationServerType(request):
    pass

def registrationServer(request):
    pass

def cmh(request):
    serverType = request.GET.get('serverType', '')
    rtime = Cmh.objects.all().values('time').latest('id')
    servers = Cmh.objects.all().order_by('serverId', '-id').distinct('serverId')
    if serverType:
        try :
            rtime = Cmh.objects.filter(serverId__serverTypeId=serverType).values('time').latest('id')
            servers = Cmh.objects.filter(serverId__serverTypeId=serverType).order_by('serverId', '-id').distinct('serverId')
        except Cmh.DoesNotExist:
            rtime = {'time' : "File does not exist"}
            servers = None
    context = {'servers' : servers, 'serverType' : serverType, 'rtime' : rtime}
    return render(request, 'fanMonitoring/cmh.html', context)

def network(request):
    serverType = request.GET.get('serverType', '')
    servers = Network.objects.all().order_by('serverId', '-id').distinct('serverId')
    if serverType:
        try :
            servers = Network.objects.filter(serverId__serverTypeId=serverType).order_by('serverId', '-id').distinct(
                'serverId')
        except Network.DoesNotExist:
            servers = None
    context = {'servers': servers, 'serverType': serverType}
    return render(request, 'fanMonitoring/network.html', context)

def iloInfo(request):
    serverType = request.GET.get('serverType', '')
    rtime = Ilo.objects.all().values('time').latest('id')
    servers = Ilo.objects.all().order_by('serverId', '-id').distinct('serverId')
    if serverType:
        try :
            rtime = Ilo.objects.filter(serverId__serverTypeId=serverType).values('time').latest('id')
            servers = Ilo.objects.filter(serverId__serverTypeId=serverType).order_by('serverId', '-id').distinct('serverId')
        except Ilo.DoesNotExist :
            rtime = {'time' : "File does not exist"}
            servers = None
    context = {'servers': servers, 'serverType': serverType, 'rtime': rtime}
    return render(request, 'fanMonitoring/ilo.html', context)

def logHome(request):
    pass

def logCmh(request):
    pass

def logNetwork(request):
    pass

def logIloInfo(request):
    pass

projects/mysite/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Monitoring System</title>
        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
        <link href="{% static 'style.css' %}" rel="stylesheet" />
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <script src="{% static 'all.js' %}" crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- Jquery -->
        <script src="{% static 'bootstrap.bundle.min.js' %}" crossorigin="anonymous"></script>
        <script src="{% static '/js/scripts.js' %}"></script>
        <script src="{% static 'Chart.min.js' %}" crossorigin="anonymous"></script>
        <script src="{% static 'assets/demo/chart-area-demo.js' %}"></script>
        <script src="{% static 'assets/demo/chart-bar-demo.js' %}"></script>
        <script src="{% static 'simple-datatables@latest' %}" crossorigin="anonymous"></script>
        <script src="{% static 'js/datatables-simple-demo.js' %}"></script>
        <script src="{% static 'jquery-3.4.1.min.js' %}"></script>
<!-- Bootstrap JS-->
        <script src="{% static 'bootstrap.min.js' %}"></script>
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!--자바스크립트 start-->
{% block script %}
{% endblock %}
<!--자바스크립트 end-->
</body>
</html>

projects/mysite/templates/base_2.html
{% load static %}
<html lang="ko">
<head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta http-equiv="refresh" content="20" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Monitoring System</title>
        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
        <link href="{% static 'style.css' %}" rel="stylesheet" />
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <script src="{% static 'all.js' %}" crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- Jquery -->
        <script src="{% static 'bootstrap.bundle.min.js' %}" crossorigin="anonymous"></script>
        <script src="{% static '/js/scripts.js' %}"></script>
        <script src="{% static 'Chart.min.js' %}" crossorigin="anonymous"></script>
        <script src="{% static 'assets/demo/chart-area-demo.js' %}"></script>
        <script src="{% static 'assets/demo/chart-bar-demo.js' %}"></script>
        <script src="{% static 'simple-datatables@latest' %}" crossorigin="anonymous"></script>
        <script src="{% static 'js/datatables-simple-demo.js' %}"></script>
        <script src="{% static 'jquery-3.4.1.min.js' %}"></script>
<!-- Bootstrap JS-->
        <script src="{% static 'bootstrap.min.js' %}"></script>
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!--자바스크립트 start-->
{% block script %}
{% endblock %}
<!--자바스크립트 end-->
</body>
</html>

projects/mysite/templates/common/login.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class="row">
        <div class="col-4">
            <h4>로그인</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:signup' %}">계정을 만드세요</a></span>
        </div> 
    </div>
    <form method="post" class="post-form" action="{% url 'common:login' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" id="username" name="username" value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <lable for="password">비밀번호</lable>
            <input type="password" class="form-control" name="password" id="password" value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}

projects/mysite/templates/common/signup.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-4">
            <h4>계정생성</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:login' %}">로그인 하세요.</a></span>
        </div>
    </div>
    <form method="post" class="post-form" action="{% url 'common:signup' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username" value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1" value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2" vlaue="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email" value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}

projects/mysite/templates/fanMonitoring/cmh.html
{% extends 'base_2.html' %}
{% block content %}

<div class="container">
    <br><br><br>
    <div class="row container-right" style="text-align:right;">
                <div style="text-align:center;">
            Recieved Time : {{ rtime.time }}
        </div>
    <form action="" mtehod="get" id="serverSelect">
        <select name="serverType" form="serverSelect">
            <option value="1">SDP</option>
            <option value="2">FDP</option>
            <option value="3">DRF</option>
            <option value="4">SDR</option>
            <option value="5">EFS</option>
            <option value="6">RCOM</option>
            <option value="7">BYP</option>
            <option value="8">TSV</option>
            <option value="9">APP</option>
            <option value="10">NMS</option>
            <option value="11">PMS</option>
            <option value="12">WAS</option>
            <option value="13">ETC</option>
        </select>
        <input class=btn-secondary type="submit">
    </form>
    </div>

    <div class="row">
                    {% for server in servers %}
        {% if forloop.counter0|divisibleby:3 %}
        <div class="col-3">
        </div>

        <div class="col-3">
            <div class="card">
                <div class="card-header" style="text-align : center;">
                    {{ server.serverId }}
                </div>
                <div class="card-body" style="text-align : center;">
                    CPU : {{ server.cpu }}
                    {% if server.cpuStatus == True %}
                    <img src="/static/green.png" width="20px" height="20px">
                    {% else %}
                    <img src="/static/red.png" width="20px" height="20px">
                    {% endif %}<br>
                    Memory : {{ server.mem }}
                    {% if server.memStatus == True %}
                    <img src="/static/green.png" width="20px" height="20px">
                    {% else %}
                    <img src="/static/red.png" width="20px" height="20px">
                    {% endif %}<br>
                    FileSystem : {{ server.hdd }}
                    {% if server.hddStatus == True %}
                    <img src="/static/green.png" width="20px" height="20px">
                    {% else %}
                    <img src="/static/red.png" width="20px" height="20px">
                    {% endif %}<br>
                </div>
            </div>
        </div>
{% else %}

        <div class="col-3">
            <div class="card">
                <div class="card-header" style="text-align : center;">
                    {{ server.serverId }}
                </div>
                <div class="card-body" style="text-align : center;">
                    CPU : {{ server.cpu }}
                    {% if server.cpuStatus == True %}
                    <img src="/static/green.png" width="20px" height="20px">
                    {% else %}
                    <img src="/static/red.png" width="20px" height="20px">
                    {% endif %}<br>
                    Memory : {{ server.mem }}
                    {% if server.memStatus == True %}
                    <img src="/static/green.png" width="20px" height="20px">
                    {% else %}
                    <img src="/static/red.png" width="20px" height="20px">
                    {% endif %}<br>
                    FileSystem : {{ server.hdd }}
                    {% if server.hddStatus == True %}
                    <img src="/static/green.png" width="20px" height="20px">
                    {% else %}
                    <img src="/static/red.png" width="20px" height="20px">
                    {% endif %}<br>
                </div>
            </div>
        </div>

        {% endif %}
                    {% endfor %}
    </div>



</div>

{% endblock %}

projects/mysite/templates/fanMonitoring/ilo.html
{% extends 'base_2.html' %}
{% block content %}

<div class="container">
    <br><br><br>
    <div class="container" style="text-align:right;">
        <div style="text-align:center;">
            Recieved Time : {{ rtime.time }}
        </div>
    <form action="" mtehod="get" id="serverSelect">
        <select name="serverType" form="serverSelect">
            <option value="1">SDP</option>
            <option value="2">FDP</option>
            <option value="3">DRF</option>
            <option value="4">SDR</option>
            <option value="5">EFS</option>
            <option value="6">RCOM</option>
            <option value="7">BYP</option>
            <option value="8">TSV</option>
            <option value="9">APP</option>
            <option value="10">NMS</option>
            <option value="11">PMS</option>
            <option value="12">WAS</option>
            <option value="13">ETC</option>
        </select>
        <input class=btn-secondary type="submit">
    </form>
    </div>
    <div class="row">
    {% for server in servers %}
        {% if forloop.counter0|divisibleby:3 or forloop.first %}
<div class="col-3"></div>


        <div class="col-3">
    <div class="card">
        <div class="card-header" style="text-align : center;">
            {{ server.serverId }}
        </div>
        <div class="card-body" style="text-align : center;">
            FAN1 speed : {{ server.fan1 }}%
            {% if server.fan1Status == True %}
            <img src="/static/green.png" width="20px" height="20px">
            {% else %}
            <img src="/static/red.png" width="20px" height="20px">
            {% endif %}<br>
            FAN2 speed : {{ server.fan2 }}%
            {% if server.fan2Status == True %}
            <img src="/static/green.png" width="20px" height="20px">
            {% else %}
            <img src="/static/red.png" width="20px" height="20px">
            {% endif %}<br>
            FAN3 speed : {{ server.fan3 }}%
            {% if server.fan3Status == True %}
            <img src="/static/green.png" width="20px" height="20px">
            {% else %}
            <img src="/static/red.png" width="20px" height="20px">
            {% endif %}<br>
            FAN4 speed : {{ server.fan4 }}%
            {% if server.fan4Status == True %}
            <img src="/static/green.png" width="20px" height="20px">
            {% else %}
            <img src="/static/red.png" width="20px" height="20px">
            {% endif %}<br>
            CPU Thermal : {{ server.cpuThermal }}℃
            {% if server.cpuThermalStatus == True %}
            <img src="/static/green.png" width="20px" height="20px">
            {% else %}
            <img src="/static/red.png" width="20px" height="20px">
            {% endif %}<br>
            Memory Thermal : {{ server.memThermal }}℃
            {% if server.memThermalStatus == True %}
            <img src="/static/green.png" width="20px" height="20px">
            {% else %}
            <img src="/static/red.png" width="20px" height="20px">
            {% endif %}<br>
        </div>
    </div>
</div>
            {% else %}
        <div class="col-3">
    <div class="card">
        <div class="card-header" style="text-align : center;">
            {{ server.serverId }}
        </div>
        <div class="card-body" style="text-align : center;">
            FAN1 speed : {{ server.fan1 }}%
            {% if server.fan1Status == True %}
            <img src="/static/green.png" width="20px" height="20px">
            {% else %}
            <img src="/static/red.png" width="20px" height="20px">
            {% endif %}<br>
            FAN2 speed : {{ server.fan2 }}%
            {% if server.fan2Status == True %}
            <img src="/static/green.png" width="20px" height="20px">
            {% else %}
            <img src="/static/red.png" width="20px" height="20px">
            {% endif %}<br>
            FAN3 speed : {{ server.fan3 }}%
            {% if server.fan3Status == True %}
            <img src="/static/green.png" width="20px" height="20px">
            {% else %}
            <img src="/static/red.png" width="20px" height="20px">
            {% endif %}<br>
            FAN4 speed : {{ server.fan4 }}%
            {% if server.fan4Status == True %}
            <img src="/static/green.png" width="20px" height="20px">
            {% else %}
            <img src="/static/red.png" width="20px" height="20px">
            {% endif %}<br>
            CPU Thermal : {{ server.cpuThermal }}℃
            {% if server.cpuThermalStatus == True %}
            <img src="/static/green.png" width="20px" height="20px">
            {% else %}
            <img src="/static/red.png" width="20px" height="20px">
            {% endif %}<br>
            Memory Thermal : {{ server.memThermal }}℃
            {% if server.memThermalStatus == True %}
            <img src="/static/green.png" width="20px" height="20px">
            {% else %}
            <img src="/static/red.png" width="20px" height="20px">
            {% endif %}<br>
        </div>
    </div>
            </div>
            {% endif %}

    {% endfor %}
</div>
</div>

{% endblock %}

projects/mysite/templates/navbar.html
        <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
            <!-- Navbar Brand-->
            <a class="navbar-brand ps-3" href="{% url 'fanMonitoring:index' %}">Monitoring System</a>
            <!-- Sidebar Toggle-->
            <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
            <!-- Navbar Search-->
<!--            <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">-->
<!--                <div class="input-group">-->
<!--                    <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />-->
<!--                    <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>-->
<!--                </div>-->
<!--            </form>-->
            <!-- Navbar-->
<!--            <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">-->
<!--                <li class="nav-item dropdown">-->
<!--                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>-->
<!--                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">-->
<!--                        <li><a class="dropdown-item" href="#!">Settings</a></li>-->
<!--                        <li><a class="dropdown-item" href="#!">Activity Log</a></li>-->
<!--                        <li><hr class="dropdown-divider" /></li>-->
<!--                        <li><a class="dropdown-item" href="#!">Logout</a></li>-->
<!--                    </ul>-->
<!--                </li>-->
<!--            </ul>-->
        </nav>
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            <div class="sb-sidenav-menu-heading">Core</div>
                            <a class="nav-link" href="{% url 'fanMonitoring:index' %}">
                                <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                                Dashboard
                            </a>
                            <div class="sb-sidenav-menu-heading">Registration</div>
                            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseLayouts">
                                <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                                Registration
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapseOne" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">
                                    <a class="nav-link" href="/admin/fanMonitoring/servertype">Server Type</a>
                                    <a class="nav-link" href="/admin/fanMonitoring/server">Servers</a>
                                </nav>
                            </div>
                            <div class="sb-sidenav-menu-heading">Monitoring</div>
                            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseLayouts">
                                <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                                Cpu / Mem / Disk
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapseTwo" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">
                                    <a class="nav-link" href="{% url 'fanMonitoring:cmh' %}">Monitoring</a>
                                    <a class="nav-link" href="/admin/fanMonitoring/cmh">Log</a>
                                </nav>
                            </div>
                            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseLayouts">
                                <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                                Network Speed
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapseThree" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">
                                    <a class="nav-link" href="{% url 'fanMonitoring:network' %}">Monitoring</a>
                                    <a class="nav-link" href="/admin/fanMonitoring/network">Log</a>
                                </nav>
                            </div>
                            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseFour" aria-expanded="false" aria-controls="collapseLayouts">
                                <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                                Fan/Thermal
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapseFour" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">
                                    <a class="nav-link" href="{% url 'fanMonitoring:iloInfo' %}">Monitoring</a>
                                    <a class="nav-link" href="/admin/fanMonitoring/ilo">Log</a>
                                </nav>
                            </div>
                            <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                    <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                                        Authentication
                                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                    </a>
                                    <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                        <nav class="sb-sidenav-menu-nested nav">
                                            <a class="nav-link" href="login.html">Login</a>
                                            <a class="nav-link" href="register.html">Register</a>
                                            <a class="nav-link" href="password.html">Forgot Password</a>
                                        </nav>
                                    </div>
                                    <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                                        Error
                                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                    </a>
                                    <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                        <nav class="sb-sidenav-menu-nested nav">
                                            <a class="nav-link" href="401.html">401 Page</a>
                                            <a class="nav-link" href="404.html">404 Page</a>
                                            <a class="nav-link" href="500.html">500 Page</a>
                                        </nav>
                                    </div>
                                </nav>
                            </div>
                        </div>
                    </div>
                </nav>
            </div>
        </div>